"""Command-line entry point for local OCR."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Sequence

from .pipeline import process_document
from .providers import (
    GLMOCRDirectReader,
    GLMOCRReader,
    LocalReader,
    PaddleOCRVLReader,
    TesseractReader,
)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Extract evidence-linked OCR JSON")
    parser.add_argument("input", type=Path, help="PDF or image to read")
    parser.add_argument("-o", "--output", type=Path, help="JSON output path")
    parser.add_argument(
        "--reader",
        choices=("tesseract", "paddleocr-vl", "glm-ocr", "glm-ocr-direct"),
        default="tesseract",
        help="Local OCR reader",
    )
    parser.add_argument("--language", default="eng", help="Tesseract language")
    parser.add_argument("--backend", default="native", help="PaddleOCR-VL backend")
    parser.add_argument("--device", help="PaddleOCR device, for example gpu:0")
    parser.add_argument(
        "--use-doc-orientation-classify",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Enable Paddle document orientation classification",
    )
    parser.add_argument(
        "--use-doc-unwarping",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Enable Paddle document unwarping",
    )
    parser.add_argument("--ocr-api-host", help="GLM-OCR SDK recognition server host")
    parser.add_argument(
        "--ocr-api-port",
        type=_positive_int,
        help="GLM-OCR SDK recognition server port",
    )
    parser.add_argument("--layout-device", help="GLM-OCR SDK layout model device")
    parser.add_argument(
        "--max-new-tokens",
        type=_positive_int,
        default=8192,
        help="Maximum tokens generated by the direct GLM-OCR model",
    )
    parser.add_argument("--dpi", type=int, default=300, help="PDF render DPI")
    args = parser.parse_args(argv)

    result = process_document(
        args.input,
        _reader_from_args(args),
        pdf_dpi=args.dpi,
    )
    payload = json.dumps(result.to_dict(), ensure_ascii=False, indent=2) + "\n"

    try:
        if args.output:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(payload, encoding="utf-8")
        else:
            sys.stdout.write(payload)
    except OSError as error:
        print(f"Could not write OCR result: {error}", file=sys.stderr)
        return 1

    return 0 if result.status == "success" else 1


def _reader_from_args(args: argparse.Namespace) -> LocalReader:
    if args.reader == "tesseract":
        return TesseractReader(language=args.language)
    if args.reader == "paddleocr-vl":
        return PaddleOCRVLReader(
            backend=args.backend,
            device=args.device,
            use_doc_orientation_classify=args.use_doc_orientation_classify,
            use_doc_unwarping=args.use_doc_unwarping,
        )
    if args.reader == "glm-ocr":
        return GLMOCRReader(
            ocr_api_host=args.ocr_api_host,
            ocr_api_port=args.ocr_api_port,
            layout_device=args.layout_device,
        )
    return GLMOCRDirectReader(max_new_tokens=args.max_new_tokens)


def _positive_int(value: str) -> int:
    number = int(value)
    if number < 1:
        raise argparse.ArgumentTypeError("value must be positive")
    return number


if __name__ == "__main__":
    raise SystemExit(main())
