"""Command-line entry point for local OCR."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Sequence

from .pipeline import process_document
from .providers import (
    GLMOCRDirectReader,
    GLMOCRReader,
    GraniteDoclingReader,
    LocalReader,
    NemotronOCRV2Reader,
    PaddleOCRVLReader,
    TesseractReader,
)

PUBLIC_COMPARATOR_READERS = {"paddleocr-vl", "glm-ocr", "glm-ocr-direct"}


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Extract evidence-linked OCR JSON")
    parser.add_argument("input", type=Path, help="PDF or image to read")
    parser.add_argument("-o", "--output", type=Path, help="JSON output path")
    parser.add_argument(
        "--reader",
        choices=(
            "tesseract",
            "paddleocr-vl",
            "glm-ocr",
            "glm-ocr-direct",
            "granite-docling",
            "nemotron-ocr-v2",
        ),
        default="tesseract",
        help="Local OCR reader",
    )
    parser.add_argument(
        "--public-comparator",
        action="store_true",
        help="Allow research-only readers that are excluded from deployment",
    )
    parser.add_argument("--language", default="eng", help="Tesseract language")
    parser.add_argument(
        "--tesseract-psm",
        type=_tesseract_psm,
        help="Tesseract page segmentation mode, from 0 to 13",
    )
    parser.add_argument(
        "--tesseract-thresholding",
        type=_tesseract_thresholding,
        help="Tesseract thresholding: 0 Otsu, 1 Adaptive Otsu, or 2 Sauvola",
    )
    parser.add_argument(
        "--nemotron-language",
        choices=("multi", "en"),
        default="multi",
        help="Nemotron OCR v2 weight variant",
    )
    parser.add_argument(
        "--nemotron-merge-level",
        choices=("word", "sentence", "paragraph"),
        default="paragraph",
        help="Nemotron OCR v2 output grouping",
    )
    parser.add_argument(
        "--batch-size",
        type=_positive_int,
        default=1,
        help="Pages per native Nemotron OCR v2 call",
    )
    parser.add_argument("--backend", default="native", help="PaddleOCR-VL backend")
    parser.add_argument("--device", help="PaddleOCR device, for example gpu:0")
    parser.add_argument(
        "--use-doc-orientation-classify",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Enable Paddle document orientation classification",
    )
    parser.add_argument(
        "--use-doc-unwarping",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Enable Paddle document unwarping",
    )
    parser.add_argument("--ocr-api-host", help="GLM-OCR SDK recognition server host")
    parser.add_argument(
        "--ocr-api-port",
        type=_positive_int,
        help="GLM-OCR SDK recognition server port",
    )
    parser.add_argument("--layout-device", help="GLM-OCR SDK layout model device")
    parser.add_argument(
        "--max-new-tokens",
        type=_positive_int,
        default=8192,
        help="Maximum tokens generated by a direct local VLM",
    )
    parser.add_argument(
        "--granite-output-format",
        choices=("text", "markdown"),
        default="text",
        help="Granite Docling serialization format",
    )
    parser.add_argument("--dpi", type=int, default=300, help="PDF render DPI")
    args = parser.parse_args(argv)

    try:
        reader = _reader_from_args(args)
    except ValueError as error:
        parser.error(str(error))
    result = process_document(args.input, reader, pdf_dpi=args.dpi)
    payload = json.dumps(result.to_dict(), ensure_ascii=False, indent=2) + "\n"

    try:
        if args.output:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(payload, encoding="utf-8")
        else:
            sys.stdout.write(payload)
    except OSError as error:
        print(f"Could not write OCR result: {error}", file=sys.stderr)
        return 1

    return 0 if result.status == "success" else 1


def _reader_from_args(args: argparse.Namespace) -> LocalReader:
    if args.reader in PUBLIC_COMPARATOR_READERS and not args.public_comparator:
        raise ValueError(
            f"Reader {args.reader!r} requires --public-comparator and is not "
            "eligible for deployment"
        )
    if args.reader == "tesseract":
        return TesseractReader(
            language=args.language,
            page_segmentation_mode=args.tesseract_psm,
            thresholding_method=args.tesseract_thresholding,
        )
    if args.reader == "paddleocr-vl":
        return PaddleOCRVLReader(
            backend=args.backend,
            device=args.device,
            use_doc_orientation_classify=args.use_doc_orientation_classify,
            use_doc_unwarping=args.use_doc_unwarping,
        )
    if args.reader == "glm-ocr":
        return GLMOCRReader(
            ocr_api_host=args.ocr_api_host,
            ocr_api_port=args.ocr_api_port,
            layout_device=args.layout_device,
        )
    if args.reader == "glm-ocr-direct":
        return GLMOCRDirectReader(max_new_tokens=args.max_new_tokens)
    if args.reader == "granite-docling":
        return GraniteDoclingReader(
            max_new_tokens=args.max_new_tokens,
            output_format=args.granite_output_format,
        )
    return NemotronOCRV2Reader(
        language=args.nemotron_language,
        merge_level=args.nemotron_merge_level,
        batch_size=args.batch_size,
    )


def _positive_int(value: str) -> int:
    number = int(value)
    if number < 1:
        raise argparse.ArgumentTypeError("value must be positive")
    return number


def _tesseract_psm(value: str) -> int:
    number = int(value)
    if not 0 <= number <= 13:
        raise argparse.ArgumentTypeError("value must be from 0 to 13")
    return number


def _tesseract_thresholding(value: str) -> int:
    number = int(value)
    if number not in {0, 1, 2}:
        raise argparse.ArgumentTypeError("value must be 0, 1, or 2")
    return number


if __name__ == "__main__":
    raise SystemExit(main())
